# Generated by Django 4.1.7 on 2023-03-22 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='PhoneNumber',
        ),
    ]
