# Generated by Django 4.1.7 on 2023-03-23 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_client_options_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('level_of_difficulty', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateTimeField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.adventuretype')),
            ],
        ),
    ]
