# Generated by Django 4.1.7 on 2023-03-23 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_adventuretype_adventure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='level_of_difficulty',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='location',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='price',
        ),
        migrations.CreateModel(
            name='CreateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateTimeField()),
                ('advanture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.adventure')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
            ],
        ),
    ]
