# Generated by Django 4.1.7 on 2023-03-26 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_eventbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='createevent',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img'),
            preserve_default=False,
        ),
    ]
